version: '3.8'

services:
  zurg:
    image: ghcr.io/debridmediamanager/zurg-testing:latest    
    container_name: zurg
    restart: unless-stopped
    ports:
      - 9999:9999
    volumes:
      - ./scripts/plex_update.sh:/app/plex_update.sh
      - ./config.yml:/app/config.yml
      - zurgdata:/app/data

  rclone:
    image: rclone/rclone:latest
    container_name: rclone
    restart: unless-stopped
    environment:
      TZ: Australia/Melbourne
      PUID: 1000
      PGID: 1000
    volumes:
      - /mnt/zurg:/data:rshared # CHANGE /mnt/zurg WITH YOUR PREFERRED MOUNT PATH
      - ./rclone.conf:/config/rclone/rclone.conf
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    depends_on:
      - zurg
        command: "mount zurghttp: /data --allow-non-empty --allow-other --uid=1000
      --gid=1000 --cache-dir /mnt/cache --vfs-cache-mode full
      --vfs-cache-max-age 24h --vfs-cache-max-size 50G --async-read
      --vfs-read-ahead 128M --vfs-read-chunk-size 64M
      --vfs-read-chunk-size-limit 2G --use-mmap --buffer-size=64M
      --dir-cache-time 10s"
volumes:
  zurgdata: null
